{
 "title": "PDC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Load Source",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_load_source", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Current Charge Source",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_charge_source", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Current Work Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_work_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Current Grid Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_lineloss1", "legendFormat": "Line 1" },
    { "expr": "pdc_lineloss2", "legendFormat": "Line 2" }
   ]
  },
  {
   "title": "Current Load Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_hasload1", "legendFormat": "Line 1" },
    { "expr": "pdc_hasload2", "legendFormat": "Line 2" }
   ]
  },
  {
   "title": "Current Overload Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pdc_overload", "legendFormat": "Overload" }
   ]
  },
  {
   "title": "Load Source",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "targets": [
    { "expr": "pdc_load_source", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Charge Source",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "targets": [
    { "expr": "pdc_charge_source", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Work Mode",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "targets": [
    { "expr": "pdc_work_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Grid Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "targets": [
    { "expr": "pdc_lineloss1", "legendFormat": "Line 1" },
    { "expr": "pdc_lineloss2", "legendFormat": "Line 2" }
   ]
  },
  {
   "title": "Load Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "targets": [
    { "expr": "pdc_hasload1", "legendFormat": "Line 1" },
    { "expr": "pdc_hasload2", "legendFormat": "Line 2" }
   ]
  },
  {
   "title": "Overload Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "targets": [
    { "expr": "pdc_overload", "legendFormat": "Status" }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pdc_battery_capacity_percent", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "pdc_battery_voltage", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "Battery Charge / Discharge Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "pdc_battery_charge_current", "legendFormat": "Charge Current" },
    { "expr": "pdc_battery_discharge_current", "legendFormat": "Discharge Current" }
   ]
  },
  { "title": "PV Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PV Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "pdc_pvinput1_voltage", "legendFormat": "Input 1" },
    { "expr": "pdc_pvinput2_voltage", "legendFormat": "Input 2" }
   ]
  },
  {
   "title": "PV Input Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "pdc_pvinput1_current", "legendFormat": "Input 1" },
    { "expr": "pdc_pvinput2_current", "legendFormat": "Input 2" }
   ]
  },
  { "title": "Grid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "pdc_grid1_voltage", "legendFormat": "Grid 1" },
    { "expr": "pdc_grid2_voltage", "legendFormat": "Grid 2" }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "pdc_grid1_frequency", "legendFormat": "Grid 1" },
    { "expr": "pdc_grid2_frequency", "legendFormat": "Grid 2" }
   ]
  },
  { "title": "AC Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "AC Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "pdc_acoutput1_voltage", "legendFormat": "Output 1" },
    { "expr": "pdc_acoutput2_voltage", "legendFormat": "Output 2" }
   ]
  },
  {
   "title": "AC Output Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "pdc_acoutput1_frequency", "legendFormat": "Output 1" },
    { "expr": "pdc_acoutput2_frequency", "legendFormat": "Output 2" }
   ]
  },
  {
   "title": "AC Output Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "expr": "pdc_acoutput1_apparent_power", "legendFormat": "Output 1" },
    { "expr": "pdc_acoutput2_apparent_power", "legendFormat": "Output 2" }
   ]
  },
  {
   "title": "AC Output Active Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "pdc_acoutput1_active_power", "legendFormat": "Output 1" },
    { "expr": "pdc_acoutput2_active_power", "legendFormat": "Output 2" }
   ]
  },
  {
   "title": "AC Output Load Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pdc_output1_load_percent", "legendFormat": "Output 1" },
    { "expr": "pdc_output2_load_percent", "legendFormat": "Output 2" }
   ]
  }
 ]
}