global:
  scrape_interval: 60s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "pdc"
    scrape_interval: 5m
    static_configs:
      - targets: ["power-datacenter-exporter:8080"]
